# Generated by Django 5.1.4 on 2025-01-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingstation',
            name='map_coordinates',
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='main.pollingstation')),
            ],
        ),
    ]
